# Generated by Django 5.2.7 on 2025-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_tax_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_address',
            field=models.TextField(blank=True, verbose_name='Dirección Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Teléfono Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_rtn',
            field=models.CharField(blank=True, max_length=25, verbose_name='RTN Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='include_client_details',
            field=models.BooleanField(default=False, verbose_name='Incluir datos de cliente'),
        ),
    ]
