# Generated by Django 4.2.7 on 2025-11-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
    ]
