# Generated by Django 5.2.7 on 2025-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
